version: "3"
services:
  web:
    build: .
    working_dir: /home/node/app
    container_name: "platzinger"
    ports:
      - "0.0.0.0:4100:4100" # ionic dev server
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "4101"